// style
import '@/globals.css'
// next api
import { Inter } from "next/font/google";
// types
import type { Metadata } from "next";
import { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface IProps {
  children: ReactNode
}

const RootLayout = (props: IProps) => {

  const { children } = props;

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export default RootLayout;
